var data = {
  philippines: {
    regions: [
      "National Capital Region (NCR) - Metro Manila",
      "Cordillera Administrative Region (CAR)",
      "Ilocos Region (Region I)",
      "Cagayan Valley (Region II)",
      "Central Luzon (Region III)",
      "Calabarzon (Region IV-A)",
      "Mimaropa (Region IV-B)",
      "Bicol Region (Region V)",
      "Western Visayas (Region VI)",
      "Central Visayas (Region VII)",
      "Eastern Visayas (Region VIII)",
      "Zamboanga Peninsula (Region IX)",
      "Northeastern Mindanao (Region X)",
      "Davao Region (Region XI)",
      "Caraga (Region XIII)"
    ],
    provinces: {
      "National Capital Region (NCR) - Metro Manila": [
        "Metro Manila"
      ],
      "Cordillera Administrative Region (CAR)": [
        "Abra",
        "Benguet",
        "Apayao",
        "Ifugao",
        "Mountain Province",
        "Bukidnon"
      ],
      "Ilocos Region (Region I)": [
        "Ilocos Norte",
        "Ilocos Sur",
        "La Union",
        "Pangasinan",
      ],
      "Cagayan Valley (Region II)":[
        "Nueva Vizcaya",
        "Batanes",
        "Isabela",
        "Quirino",
        "Cagayan"
      ],
      "Central Luzon (Region III)": [
        "Aurora",
        "Tarlac",
        "Zambales",
        "Pampanga",
        "Bulacan",
        "Nueva Ecija",
        "Bataan"
      ],
      "Calabarzon (Region IV-A)": [
        "Batangas",
        "Cavite",
        "Laguna",
        "Quezon Province",
        "Rizal"
      ],
      "Mimaropa (Region IV-B)": [
        "Oriental Mindoro",
        "Occidental Mindoro",
        "Marinduque",
        "Palawan",
        "Romblon"
      ],
      "Bicol Region (Region V)":[
        "Albay",
        "Sorsogon",
        "Camarines Sur",
        "Camarines North",
        "Catanduanes",
        "Masbate"
      ],
      "Western Visayas (Region VI)": [
        "Aklan",
        "Antique",
        "Capiz",
        "Guimaras",
        "Iloilo",
        "Negros Occidental"
      ],
      "Central Visayas (Region VII)":[
        "Cebu",
        "Bohol",
        "Negros Oriental",
      ],
      "Eastern Visayas (Region VIII)":[
        "Biliran",
        "Eastern Samar",
        "Leyte",
        "Samar",
        "Southern Samar",
        "Southern Leyte"
      ],
      "Zamboanga Peninsula (Region IX)" :[
        "Zamboanga del Norte",
        "Zamboanga del Sur",
        "Zambonga Sibungay"
      ],
      "Northeastern Mindanao (Region X)":[
        "Bukidnon",
        "Camiguin",
        "Lanao Del Norte",
        "Misamis Occidental",
        "Misamis Oriental",
      ],
      "Davao Region (Region XI)":[
        "Davao City",
        "Davao Del Sur",
        "Compostela Valley",
        "Davao De Oro"
      ],
      "Soocksargen (Region XII)":[
        "Cotabato",
        "Sultan Kudarat",
        "Saraagni",
        "South Cotabato"
      ],
      "Caraga (Region XIII)":[
        "Agusan Del Norte",
        "Surigao del Norte",
        "Surigao del Sur",
        "Dinagat Islands",
      ],
      "BARMM":[
        "Basilan",
        "Maguindanao",
        "Sulu",
        "Tawi-Tawi"
      ]
    },
    cities: {
      "Metro Manila": [
        "Manila",
        "Quezon City",
        "Makati",
        "Taguig",
        "Pasig",
        "Parañaque",
        "Marikina",
        "Caloocan",
        "Las Pinas",
        "Valenzuela",
      ],
      "Abra": [
        "Bangued",
        "Iriga",
        "Pangasinan",
        "Bucay",
        "Lagayan",
        "Dolores"
      ],
      "Benguet": [
        "Laoag",
        "Baguio City",
        "La Trinidad",
        "Kubingan"
      ],
      "Apayao":[
        "Kabugao"
      ],
      "Ifugao":[
        "Banaue",
        "Kiangan"
      ],
      "Mountain Province":[
        "Mayon Volcano National Park",
        "Sagada",
        "Bontoc"
      ],
      "Bukidnon":[
        "Malaybay City",
        "Valnencia City"
      ],
      "Ilocos Norte": [
        "Laoag City",
        "Batac City",
        "Badoc",
        "Paoay",
        "Dingras"
      ],
      "Ilocos Sur": [
        "Vigan City",
        "Candon City",
        "Narvacan",
        "Santa",
        "Bantay"
      ],
      "La Union": [
        "San Fernando City",
        "Agoo",
        "Bauang",
        "San Juan",
        "Rosario"
      ],
      "Pangasinan": [
        "Lingayen",
        "Dagupan City",
        "Urdaneta City",
        "Mangaldan",
        "San Carlos City"
      ],
      "Nueva Vizcaya": [
        "Bayombong",
        "Solano",
        "Dupax del Norte",
        "Aritao",
        "Bambang"
      ],
      "Batanes": [
        "Basco",
        "Ivana",
        "Mahatao",
        "Uyugan",
        "Sabtang"
      ],
      "Isabela": [
        "Ilagan City",
        "Cauayan City",
        "Santiago City",
        "Alicia",
        "Cabagan"
      ],
      "Quirino": [
        "Cabarroguis",
        "Diffun",
        "Maddela",
        "Aglipay",
        "Nagtipunan"
      ],
      "Cagayan": [
        "Abulug",
        "Alcala",
        "Allacapan",
        "Amulung",
        "Aparri",
        "Baggao",
        "Ballesteros",
        "Buguey",
        "Calayan",
        "Camalaniugan",
        "Claveria",
        "Enrile",
        "Gattaran",
        "Gonzaga",
        "Iguig",
        "Lal-Lo",
        "Lasam",
        "Pamplona",
        "Peñablanca",
        "Piat",
        "Rizal",
        "Sanchez-Mira",
        "Santa Ana",
        "Santa Praxedes",
        "Santa Teresita",
        "Santo Niño",
        "Solana",
        "Tuguegarao City"
      ],
      "Aurora": [
        "Baler",
        "Casiguran",
        "Dilasag",
        "Dinalungan",
        "Dingalan",
        "Maria Aurora",
        "San Luis"
      ],
      "Tarlac": [
        "Anao",
        "Bamban",
        "Camiling",
        "Capas",
        "Concepcion",
        "Gerona",
        "La Paz",
        "Mayantoc",
        "Moncada",
        "Paniqui",
        "Pura",
        "Ramos",
        "San Clemente",
        "San Jose",
        "San Manuel",
        "Santa Ignacia",
        "Tarlac City",
        "Victoria"
      ],
      "Zambales": [
        "Botolan",
        "Cabangan",
        "Candelaria",
        "Castillejos",
        "Iba",
        "Masinloc",
        "Olongapo City",
        "Palauig",
        "San Antonio",
        "San Felipe",
        "San Marcelino",
        "San Narciso",
        "Santa Cruz",
        "Subic"
      ],
      "Pampanga": [
        "Angeles City",
        "Apalit",
        "Arayat",
        "Bacolor",
        "Candaba",
        "Floridablanca",
        "Guagua",
        "Lubao",
        "Mabalacat City",
        "Macabebe",
        "Magalang",
        "Masantol",
        "Mexico",
        "Minalin",
        "Porac",
        "San Fernando City",
        "San Luis",
        "San Simon",
        "Santa Ana",
        "Santa Rita",
        "Santo Tomas",
        "Sasmuan"
      ],
      "Bulacan": [
        "Angat",
        "Balagtas",
        "Baliuag",
        "Bocaue",
        "Bulakan",
        "Bustos",
        "Calumpit",
        "Dona Remedios Trinidad",
        "Guiguinto",
        "Hagonoy",
        "Malolos City",
        "Marilao",
        "Meycauayan City",
        "Norzagaray",
        "Obando",
        "Pandi",
        "Paombong",
        "Plaridel",
        "Pulilan",
        "San Ildefonso",
        "San Jose del Monte City",
        "San Miguel",
        "San Rafael",
        "Santa Maria"
      ],
      "Nueva Ecija": [
        "Aliaga",
        "Bongabon",
        "Cabanatuan City",
        "Cabiao",
        "Carranglan",
        "Cuyapo",
        "Gabaldon",
        "Gapan City",
        "General Mamerto Natividad",
        "General Tinio",
        "Guimba",
        "Jaen",
        "Laur",
        "Licab",
        "Llanera",
        "Lupao",
        "Nampicuan",
        "Palayan City",
        "Pantabangan",
        "Peñaranda",
        "Quezon",
        "Rizal",
        "San Antonio",
        "San Isidro",
        "San Jose City",
        "San Leonardo",
        "Santa Rosa",
        "Santo Domingo",
        "Talavera",
        "Talugtug",
        "Zaragoza"
      ],
      "Bataan": [
        "Balanga City",
        "Abucay",
        "Bagac",
        "Dinalupihan",
        "Hermosa",
        "Limay",
        "Mariveles",
        "Morong",
        "Orani",
        "Orion",
        "Pilar",
        "Samal"
      ],
      "Batangas": [
        "Agoncillo",
        "Alitagtag",
        "Balayan",
        "Balete",
        "Batangas City",
        "Bauan",
        "Calaca",
        "Calatagan",
        "Cuenca",
        "Ibaan",
        "Laurel",
        "Lemery",
        "Lian",
        "Lipa City",
        "Lobo",
        "Mabini",
        "Malvar",
        "Mataasnakahoy",
        "Nasugbu",
        "Padre Garcia",
        "Rosario",
        "San Jose",
        "San Juan",
        "San Luis",
        "San Nicolas",
        "San Pascual",
        "Santa Teresita",
        "Santo Tomas",
        "Taal",
        "Talisay",
        "Tanauan City",
        "Taysan",
        "Tingloy",
        "Tuy"
      ],
      "Cavite": [
        "Alfonso",
        "Amadeo",
        "Bacoor",
        "Carmona",
        "Cavite City",
        "Dasmarinas City",
        "General Emilio Aguinaldo",
        "General Mariano Alvarez",
        "General Trias",
        "Imus",
        "Indang",
        "Kawit",
        "Magallanes",
        "Maragondon",
        "Mendez",
        "Naic",
        "Noveleta",
        "Rosario",
        "Silang",
        "Tagaytay City",
        "Tanza",
        "Ternate",
        "Trece Martires City"
      ],
      "Laguna": [
        "Alaminos",
        "Bay",
        "Biñan City",
        "Cabuyao City",
        "Calamba City",
        "Calauan",
        "Cavinti",
        "Famy",
        "Kalayaan",
        "Liliw",
        "Los Baños",
        "Luisiana",
        "Lumban",
        "Mabitac",
        "Magdalena",
        "Majayjay",
        "Nagcarlan",
        "Paete",
        "Pagsanjan",
        "Pakil",
        "Pangil",
        "Pila",
        "Rizal",
        "San Pablo City",
        "San Pedro",
        "Santa Cruz",
        "Santa Maria",
        "Santa Rosa City",
        "Siniloan",
        "Victoria"
      ],
      "Quezon Province": [
        "Agdangan",
        "Alabat",
        "Atimonan",
        "Buenavista",
        "Burdeos",
        "Calauag",
        "Candelaria",
        "Catanauan",
        "Dolores",
        "General Luna",
        "General Nakar",
        "Guinayangan",
        "Gumaca",
        "Infanta",
        "Jomalig",
        "Lopez",
        "Lucban",
        "Lucena City",
        "Macalelon",
        "Mauban",
        "Mulanay",
        "Padre Burgos",
        "Pagbilao",
        "Panukulan",
        "Patnanungan",
        "Perez",
        "Pitogo",
        "Plaridel",
        "Polillo",
        "Quezon",
        "Real",
        "Sampaloc",
        "San Andres",
        "San Antonio",
        "San Francisco",
        "San Narciso",
        "Sariaya",
        "Tagkawayan",
        "Tiaong",
        "Unisan"
      ],
      "Rizal": [
        "Angono",
        "Antipolo City",
        "Baras",
        "Binangonan",
        "Cainta",
        "Cardona",
        "Jalajala",
        "Morong",
        "Pililla",
        "Rodriguez (Montalban)",
        "San Mateo",
        "Tanay",
        "Taytay",
        "Teresa"
      ],
      "Oriental Mindoro": [
        "Baco",
        "Bansud",
        "Bongabong",
        "Bulalacao",
        "Calapan City",
        "Gloria",
        "Mansalay",
        "Naujan",
        "Pinamalayan",
        "Pola",
        "Puerto Galera",
        "Roxas",
        "San Teodoro",
        "Socorro",
        "Victoria"
      ],
      "Occidental Mindoro": [
        "Abra de Ilog",
        "Calintaan",
        "Looc",
        "Lubang",
        "Magsaysay",
        "Mamburao",
        "Paluan",
        "Rizal",
        "Sablayan",
        "San Jose",
        "Santa Cruz"
      ],
      "Marinduque": [
        "Boac",
        "Buenavista",
        "Gasan",
        "Mogpog",
        "Santa Cruz",
        "Torrijos"
      ],
      "Palawan": [
        "Aborlan",
        "Agutaya",
        "Araceli",
        "Balabac",
        "Bataraza",
        "Brooke's Point",
        "Busuanga",
        "Cagayancillo",
        "Coron",
        "Culion",
        "Cuyo",
        "Dumaran",
        "El Nido",
        "Kalayaan",
        "Linapacan",
        "Magsaysay",
        "Narra",
        "Puerto Princesa City",
        "Quezon",
        "Rizal",
        "Roxas",
        "San Vicente",
        "Sofronio Española",
        "Taytay"
      ],
      "Romblon": [
        "Alcantara",
        "Banton",
        "Cajidiocan",
        "Calatrava",
        "Concepcion",
        "Corcuera",
        "Ferrol",
        "Looc",
        "Magdiwang",
        "Odiongan",
        "Romblon"
      ],
      "Albay": [
        "Bacacay",
        "Camalig",
        "Daraga",
        "Guinobatan",
        "Jovellar",
        "Legazpi City",
        "Libon",
        "Ligao City",
        "Malilipot",
        "Malinao",
        "Manito",
        "Oas",
        "Pio Duran",
        "Polangui",
        "Rapu-Rapu",
        "Santo Domingo (Libog)"
      ],
      "Sorsogon": [
        "Barcelona",
        "Bulan",
        "Bulusan",
        "Casiguran",
        "Castilla",
        "Donsol",
        "Gubat",
        "Irosin",
        "Juban",
        "Magallanes",
        "Matnog",
        "Pilar",
        "Prieto Diaz",
        "Santa Magdalena",
        "Sorsogon City"
      ],
      "Camarines Sur": [
        "Baao",
        "Balatan",
        "Bato",
        "Bombon",
        "Buhi",
        "Bula",
        "Cabusao",
        "Calabanga",
        "Camaligan",
        "Canaman",
        "Caramoan",
        "Del Gallego",
        "Gainza",
        "Garchitorena",
        "Goa",
        "Iriga City",
        "Lagonoy",
        "Libmanan",
        "Lupi",
        "Magarao",
        "Milaor",
        "Minalabac",
        "Nabua",
        "Naga City",
        "Ocampo",
        "Pamplona",
        "Pasacao",
        "Pili",
        "Presentacion",
        "Ragay",
        "Sagnay",
        "San Fernando",
        "San Jose",
        "Sipocot",
        "Siruma",
        "Tigaon",
        "Tinambac"
      ],
      "Camarines North": [
        "Basud",
        "Capalonga",
        "Daet",
        "Jose Panganiban",
        "Labo",
        "Mercedes",
        "Paracale",
        "San Lorenzo Ruiz",
        "San Vicente",
        "Santa Elena",
        "Talisay",
        "Vinzons"
      ],
      "Catanduanes": [
        "Bagamanoc",
        "Baras",
        "Bato",
        "Caramoran",
        "Gigmoto",
        "Pandan",
        "Panganiban (Payo)",
        "San Andres",
        "San Miguel",
        "Viga",
        "Virac (Capital)"
      ],
      "Masbate": [
        "Aroroy",
        "Baleno",
        "Balud",
        "Batuan",
        "Cataingan",
        "Cawayan",
        "Claveria",
        "Dimasalang",
        "Esperanza",
        "Mandaon",
        "Masbate City",
        "Milagros",
        "Mobo",
        "Monreal",
        "Palanas",
        "Pio V. Corpuz",
        "Placer",
        "San Fernando",
        "San Jacinto",
        "San Pascual",
        "Uson"
      ],
      "Aklan": [
        "Altavas",
        "Balete",
        "Banga",
        "Batan",
        "Buruanga",
        "Ibajay",
        "Kalibo",
        "Lezo",
        "Libacao",
        "Madalag",
        "Makato",
        "Malay",
        "Malinao",
        "Nabas",
        "New Washington",
        "Numancia",
        "Tangalan"
      ],
      "Antique": [
        "Anini-y",
        "Barbaza",
        "Belison",
        "Bugasong",
        "Caluya",
        "Culasi",
        "Hamtic",
        "Laua-an",
        "Libertad",
        "Pandan",
        "Patnongon",
        "San Jose de Buenavista",
        "San Remigio",
        "Sebaste",
        "Sibalom",
        "Tibiao",
        "Tobias Fornier",
        "Valderrama"
      ],
      "Capiz": [
        "Cuartero",
        "Dao",
        "Dumalag",
        "Dumarao",
        "Ivisan",
        "Jamindan",
        "Maayon",
        "Mambusao",
        "Panay",
        "Panitan",
        "Pilar",
        "Pontevedra",
        "President Roxas",
        "Roxas City (Capital)",
        "Sapi-an",
        "Sigma",
        "Tapaz"
      ],
      "Guimaras": [
        "Buenavista",
        "Jordan",
        "Nueva Valencia",
        "San Lorenzo",
        "Sibunag"
      ],
      "Iloilo": [
        "Ajuy",
        "Alimodian",
        "Anilao",
        "Badiangan",
        "Balasan",
        "Banate",
        "Barotac Nuevo",
        "Barotac Viejo",
        "Batad",
        "Bingawan",
        "Cabatuan",
        "Calinog",
        "Carles",
        "Concepcion",
        "Dingle",
        "Dueñas",
        "Dumangas",
        "Estancia",
        "Guimbal",
        "Igbaras",
        "Iloilo City",
        "Janiuay",
        "Lambunao",
        "Leganes",
        "Lemery",
        "Leon",
        "Maasin",
        "Miagao",
        "Mina",
        "New Lucena",
        "Oton",
        "Passi City",
        "Pavia",
        "Pototan",
        "San Dionisio",
        "San Enrique",
        "San Joaquin",
        "San Miguel",
        "San Rafael",
        "Santa Barbara",
        "Sara",
        "Tigbauan",
        "Tubungan",
        "Zarraga"
      ],
      "Negros Occidental": [
        "Bacolod City",
        "Bago City",
        "Binalbagan",
        "Cadiz City",
        "Calatrava",
        "Candoni",
        "Cauayan",
        "Enrique B. Magalona",
        "Escalante City",
        "Himamaylan City",
        "Hinigaran",
        "Hinoba-an",
        "Ilog",
        "Isabela",
        "Kabankalan City",
        "La Carlota City",
        "La Castellana",
        "Manapla",
        "Moises Padilla",
        "Murcia",
        "Pontevedra",
        "Pulupandan",
        "Sagay City",
        "Salvador Benedicto",
        "San Carlos City",
        "San Enrique",
        "Silay City",
        "Sipalay City",
        "Talisay City",
        "Toboso",
        "Valladolid",
        "Victorias City"
      ],
      "Cebu": [
        "Alcantara",
        "Alcoy",
        "Alegria",
        "Aloguinsan",
        "Argao",
        "Asturias",
        "Badian",
        "Balamban",
        "Bantayan",
        "Barili",
        "Bogo City",
        "Boljoon",
        "Borbon",
        "Carcar City",
        "Carmen",
        "Catmon",
        "Cebu City",
        "Compostela",
        "Consolacion",
        "Cordova",
        "Daanbantayan",
        "Dalaguete",
        "Danao City",
        "Dumanjug",
        "Ginatilan",
        "Lapu-Lapu City",
        "Liloan",
        "Madridejos",
        "Malabuyoc",
        "Mandaue City",
        "Medellin",
        "Minglanilla",
        "Moalboal",
        "Naga City",
        "Oslob",
        "Pilar",
        "Pinamungajan",
        "Poro",
        "Ronda",
        "Samboan",
        "San Fernando",
        "San Francisco",
        "San Remigio",
        "Santa Fe",
        "Santander",
        "Sibonga",
        "Sogod",
        "Tabogon",
        "Tabuelan",
        "Talisay City",
        "Toledo City",
        "Tuburan",
        "Tudela"
      ],
      "Bohol": [
        "Alburquerque",
        "Alicia",
        "Anda",
        "Antequera",
        "Baclayon",
        "Balilihan",
        "Batuan",
        "Bien Unido",
        "Bilar",
        "Buenavista",
        "Calape",
        "Candijay",
        "Carmen",
        "Catigbian",
        "Clarin",
        "Corella",
        "Cortes",
        "Dagohoy",
        "Danao",
        "Dauis",
        "Dimiao",
        "Duero",
        "Garcia Hernandez",
        "Getafe",
        "Guindulman",
        "Inabanga",
        "Jagna",
        "Jetafe",
        "Lila",
        "Loay",
        "Loboc",
        "Loon",
        "Mabini",
        "Maribojoc",
        "Panglao",
        "Pilar",
        "Pres. Carlos P. Garcia",
        "Sagbayan",
        "San Isidro",
        "San Miguel",
        "Sevilla",
        "Sierra Bullones",
        "Sikatuna",
        "Tagbilaran City (Capital)",
        "Talibon",
        "Trinidad",
        "Tubigon",
        "Ubay",
        "Valencia"
      ],
      "Negros Oriental": [
        "Amlan",
        "Ayungon",
        "Bacong",
        "Bais City",
        "Basay",
        "Bayawan City",
        "Bindoy",
        "Canlaon City",
        "Dauin",
        "Dumaguete City (Capital)",
        "Guihulngan City",
        "Jimalalud",
        "La Libertad",
        "Mabinay",
        "Manjuyod",
        "Pamplona",
        "San Jose",
        "Santa Catalina",
        "Siaton",
        "Sibulan",
        "Tanjay City",
        "Tayasan",
        "Valencia",
        "Vallehermoso",
        "Zamboanguita"
      ],
      "Siquijor": [
        "Enrique Villanueva",
        "Larena",
        "Lazi",
        "Maria",
        "San Juan",
        "Siquijor (Capital)"
      ],
      "Biliran": [
        "Almeria",
        "Biliran (Capital)",
        "Cabucgayan",
        "Caibiran",
        "Culaba",
        "Kawayan",
        "Maripipi",
        "Naval"
      ],
      "Eastern Samar": [
        "Arteche",
        "Balangiga",
        "Balangkayan",
        "Borongan City (Capital)",
        "Can-avid",
        "Dolores",
        "General MacArthur",
        "Giporlos",
        "Guiuan",
        "Hernani",
        "Jipapad",
        "Lawaan",
        "Llorente",
        "Maslog",
        "Maydolong",
        "Mercedes",
        "Oras",
        "Quinapondan",
        "Salcedo",
        "San Julian",
        "San Policarpo",
        "Sulat",
        "Taft"
      ],
      "Leyte": [
        "Abuyog",
        "Alangalang",
        "Albuera",
        "Babatngon",
        "Barugo",
        "Bato",
        "Baybay City",
        "Burauen",
        "Calubian",
        "Capoocan",
        "Carigara",
        "Dagami",
        "Dulag",
        "Hilongos",
        "Hindang",
        "Inopacan",
        "Isabel",
        "Jaro",
        "Javier",
        "Julita",
        "Kananga",
        "La Paz",
        "Leyte",
        "MacArthur",
        "Mahaplag",
        "Matag-ob",
        "Matalom",
        "Mayorga",
        "Merida",
        "Ormoc City",
        "Palo",
        "Palompon",
        "Pastrana",
        "San Isidro",
        "San Miguel",
        "Santa Fe",
        "Tabango",
        "Tabontabon",
        "Tacloban City",
        "Tanauan",
        "Tolosa",
        "Tunga",
        "Villaba"
      ],
      "Samar": [
        "Almagro",
        "Basey",
        "Calbayog City",
        "Calbiga",
        "Catbalogan City (Capital)",
        "Daram",
        "Gandara",
        "Hinabangan",
        "Jiabong",
        "Marabut",
        "Matuguinao",
        "Motiong",
        "Pagsanghan",
        "Paranas",
        "Pinabacdao",
        "San Jorge",
        "San Jose de Buan",
        "San Sebastian",
        "Santa Margarita",
        "Santa Rita",
        "Santo Niño",
        "Tagapul-an",
        "Talalora",
        "Tarangnan",
        "Villareal",
        "Zumarraga"
      ],
      "Southern Samar": [
        "Anahawan",
        "Balangiga",
        "Balaoan",
        "Barobo",
        "Borongan City",
        "Can-avid",
        "Dolores",
        "General MacArthur",
        "Giporlos",
        "Guiuan",
        "Hernani",
        "Jipapad",
        "Lawaan",
        "Llorente",
        "Maslog",
        "Maydolong",
        "Mercedes",
        "Oras",
        "Quinapondan",
        "Salcedo",
        "San Julian",
        "San Policarpo",
        "Sulat",
        "Taft"
      ],
      "Southern Leyte": [
        "Anahawan",
        "Bontoc",
        "Hinunangan",
        "Hinundayan",
        "Libagon",
        "Liloan",
        "Limasawa",
        "Maasin City (Capital)",
        "Macrohon",
        "Malitbog",
        "Padre Burgos",
        "Pintuyan",
        "Saint Bernard",
        "San Francisco",
        "San Juan",
        "San Ricardo",
        "Silago",
        "Sogod",
        "Tomas Oppus"
      ],
      "Zamboanga del Norte": [
        "Baliguian",
        "Godod",
        "Gutalac",
        "Jose Dalman",
        "Kalawit",
        "Katipunan",
        "La Libertad",
        "Labason",
        "Leon B. Postigo",
        "Liloy",
        "Manukan",
        "Mutia",
        "Piñan",
        "Polanco",
        "President Manuel A. Roxas",
        "Rizal",
        "Salug",
        "Sergio Osmeña Sr.",
        "Siayan",
        "Sibuco",
        "Sibutad",
        "Sindangan",
        "Siocon",
        "Sirawai",
        "Tampilisan"
      ],
      "Zamboanga del Sur": [
        "Aurora",
        "Bayog",
        "Dimataling",
        "Dinas",
        "Dumalinao",
        "Dumingag",
        "Guipos",
        "Josefina",
        "Kumalarang",
        "Labangan",
        "Lakewood",
        "Lapuyan",
        "Mahayag",
        "Margosatubig",
        "Midsalip",
        "Molave",
        "Pagadian City",
        "Pitogo",
        "Ramon Magsaysay",
        "San Miguel",
        "San Pablo",
        "Sominot",
        "Tabina",
        "Tambulig",
        "Tigbao",
        "Tukuran",
        "Vincenzo A. Sagun"
      ],
      "Zamboanga Sibugay": [
        "Alicia",
        "Buug",
        "Diplahan",
        "Imelda",
        "Ipil",
        "Kabasalan",
        "Mabuhay",
        "Malangas",
        "Naga",
        "Olutanga",
        "Payao",
        "Roseller T. Lim",
        "Siay",
        "Talusan",
        "Titay",
        "Tungawan"
      ],
      "Bukidnon": [
        "Baungon",
        "Cabanglasan",
        "Damulog",
        "Dangcagan",
        "Don Carlos",
        "Don Victoriano Chiongbian",
        "Impasugong",
        "Kadingilan",
        "Kalilangan",
        "Kibawe",
        "Kitaotao",
        "Lantapan",
        "Libona",
        "Malaybalay City (Capital)",
        "Malitbog",
        "Manolo Fortich",
        "Maramag",
        "Pangantucan",
        "Quezon",
        "San Fernando",
        "Sumilao",
        "Talakag",
        "Valencia City"
      ],
      "Camiguin": [
        "Catarman",
        "Guinsiliban",
        "Mahinog",
        "Mambajao (Capital)",
        "Sagay"
      ],
      "Lanao Del Norte": [
        "Bacolod",
        "Baloi",
        "Baroy",
        "Kapatagan",
        "Kauswagan",
        "Kolambugan",
        "Lala",
        "Linamon",
        "Magsaysay",
        "Maigo",
        "Matungao",
        "Munai",
        "Nunungan",
        "Pantao Ragat",
        "Pantar",
        "Poona Piagapo",
        "Salvador",
        "Sapad",
        "Sultan Naga Dimaporo",
        "Tagoloan",
        "Tangcal",
        "Tubod (Capital)"
      ],
      "Misamis Occidental": [
        "Aloran",
        "Baliangao",
        "Bonifacio",
        "Calamba",
        "Clarin",
        "Concepcion",
        "Don Victoriano Chiongbian",
        "Jimenez",
        "Lopez Jaena",
        "Oroquieta City (Capital)",
        "Ozamiz City",
        "Panaon",
        "Plaridel",
        "Sapang Dalaga",
        "Sinacaban",
        "Tangub City",
        "Tudela"
      ],
      "Misamis Oriental": [
        "Alubijid",
        "Balingasag",
        "Balingoan",
        "Binuangan",
        "Cagayan de Oro City",
        "Claveria",
        "El Salvador City",
        "Gingoog City",
        "Gitagum",
        "Initao",
        "Jasaan",
        "Kinoguitan",
        "Lagonglong",
        "Laguindingan",
        "Libertad",
        "Lugait",
        "Magsaysay",
        "Manticao",
        "Medina",
        "Naawan",
        "Opol",
        "Salay",
        "Sugbongcogon",
        "Tagoloan",
        "Talisayan",
        "Villanueva"
      ],
      "Davao City": [
        "Baguio District",
        "Buhangin",
        "Bunawan",
        "Calinan",
        "Carmen",
        "Catalunan Grande",
        "Catalunan Pequeno",
        "District A",
        "District B",
        "District C",
        "District D",
        "District E",
        "District F",
        "District G",
        "District H",
        "District I",
        "District J",
        "District K",
        "District L",
        "District M",
        "District N",
        "District O",
        "District P",
        "District Q",
        "District R",
        "District S",
        "District T",
        "District U",
        "District V",
        "District W",
        "District X",
        "District Y",
        "District Z",
        "Maa",
        "Mabini",
        "Pampanga",
        "Paquibato",
        "Sasa",
        "Subasta Han",
        "Sumimao"
      ],
      "Davao Del Sur": [
        "Bansalan",
        "Davao City",
        "Digos City (Capital)",
        "Hagonoy",
        "Kiblawan",
        "Magsaysay",
        "Malalag",
        "Matanao",
        "Padada",
        "Santa Cruz",
        "Sulop"
      ],
      "Compostela Valley": [
        "Compostela",
        "Laak (San Vicente)",
        "Mabini (Dona Alicia)",
        "Maco",
        "Maragusan (San Mariano)",
        "Mawab",
        "Monkayo",
        "Montevista",
        "Nabunturan (Capital)",
        "New Bataan",
        "Pantukan"
      ],
      "Davao De Oro": [
        "Compostela",
        "Laak (San Vicente)",
        "Mabini (Dona Alicia)",
        "Maco",
        "Maragusan (San Mariano)",
        "Mawab",
        "Monkayo",
        "Montevista",
        "Nabunturan (Capital)",
        "New Bataan",
        "Pantukan"
      ],
      "Cotabato": [
        "Alamada",
        "Aleosan",
        "Antipas",
        "Arakan",
        "Banisilan",
        "Carmen",
        "Kabacan",
        "Kidapawan City (Capital)",
        "Libungan",
        "M'lang",
        "Magpet",
        "Makilala",
        "Matalam",
        "Midsayap",
        "Pigcawayan",
        "Pikit",
        "President Roxas",
        "Tulunan"
      ],
      "Sultan Kudarat": [
        "Bagumbayan",
        "Columbio",
        "Esperanza",
        "Isulan (Capital)",
        "Kalamansig",
        "Lambayong (Maranding)",
        "Lebak",
        "Lutayan",
        "Palimbang",
        "President Quirino",
        "Senator Ninoy Aquino"
      ],
      "Sarangani": [
        "Alabel (Capital)",
        "Glan",
        "Kiamba",
        "Maasim",
        "Maitum",
        "Malapatan"
      ],
      "South Cotabato": [
        "Banga",
        "General Santos City",
        "Koronadal City (Capital)",
        "Lake Sebu",
        "Norala",
        "Polomolok",
        "Santo Niño",
        "Surallah",
        "T'Boli",
        "Tampakan",
        "Tantangan",
        "Tupi"
      ],
      "Agusan Del Norte": [
        "Buenavista",
        "Butuan City (Capital)",
        "Cabadbaran City",
        "Carmen",
        "Jabonga",
        "Kitcharao",
        "Las Nieves",
        "Magallanes",
        "Nasipit",
        "Remedios T. Romualdez",
        "Santiago",
        "Tubay"
      ],
      "Surigao del Norte": [
        "Alegria",
        "Bacuag",
        "Burgos",
        "Claver",
        "Dapa",
        "Del Carmen",
        "General Luna",
        "Gigaquit",
        "Mainit",
        "Malimono",
        "Pilar",
        "Placer",
        "San Benito",
        "San Francisco",
        "San Isidro",
        "Santa Monica",
        "Sison",
        "Socorro",
        "Surigao City (Capital)",
        "Tagana-an",
        "Tubod"
      ],
      "Surigao del Sur": [
        "Barobo",
        "Bayabas",
        "Bislig City",
        "Cagwait",
        "Cantilan",
        "Carmen",
        "Carrascal",
        "Cortes",
        "Hinatuan",
        "Lanuza",
        "Lianga",
        "Lingig",
        "Madrid",
        "Marihatag",
        "San Agustin",
        "San Miguel",
        "Tagbina",
        "Tandag City (Capital)"
      ],
      "Dinagat Islands": [
        "Basilisa",
        "Cagdianao",
        "Dinagat",
        "Libjo (Albor)",
        "Loreto",
        "San Jose (Capital)"
      ]
    }
  }
};


function updateDropdown(dropdownId, options) {
  var dropdown = document.getElementById(dropdownId);

  dropdown.innerHTML = "<option value='' disabled selected>Select " + dropdownId.charAt(0).toUpperCase() + dropdownId.slice(1) + "</option>";

  options.forEach(option => {
    var optionElement = document.createElement("option");
    optionElement.value = option;
    optionElement.text = option;
    dropdown.add(optionElement);
  });
}

function updateProvinces() {
  var regionDropdown = document.getElementById('region');
  var selectedRegion = regionDropdown.value;
  var provinceDropdown = document.getElementById('province');
  var cityDropdown = document.getElementById('city');

  provinceDropdown.innerHTML = "<option value='' disabled selected>Select Province</option>";
  cityDropdown.innerHTML = "<option value='' disabled selected>Select City</option>";

  if (data.philippines.provinces[selectedRegion]) {
    updateDropdown('province', data.philippines.provinces[selectedRegion]);
  }

  updateCities();
}

function updateCities() {
  var provinceDropdown = document.getElementById('province');
  var selectedProvince = provinceDropdown.value;
  var cityDropdown = document.getElementById('city');

  cityDropdown.innerHTML = "<option value='' disabled selected>Select City</option>";

  if (data.philippines.cities[selectedProvince]) {
    updateDropdown('city', data.philippines.cities[selectedProvince]);
  }
}

window.onload = function () {
    updateDropdown('region', data.philippines.regions);
};
